### ISSUE TITLE
Manual build instructions fail:

### ISSUE THREAD

**Issue by catid** [mirage-project/mirage#8]
Installed /home/catid/mambaforge/envs/mirage/lib/python3.10/site-packages/mirage-0.1.0-py3.10-linux-x86_64.egg
Processing dependencies for mirage==0.1.0
Finished processing dependencies for mirage==0.1.0
(mirage) ➜  python git:(main) ✗ cd ..
(mirage) ➜  mirage git:(main) ✗ ls
build  cmake  CMakeLists.txt  config.cmake  cpp_examples  demo  deps  docker  img  include  INSTALL.md  LICENSE  python  README.md  scripts  src  tests
(mirage) ➜  mirage git:(main) ✗ python demo/demo_group_query_attention_spec_decode.py --checkpoint demo/checkpoint_group_query_attn_spec_decode.json
Traceback (most recent call last):
  File "/home/catid/sources/mirage/demo/demo_group_query_attention_spec_decode.py", line 1, in <module>
    import mirage as mi
  File "/home/catid/mambaforge/envs/mirage/lib/python3.10/site-packages/mirage-0.1.0-py3.10.egg/mirage/__init__.py", line 1, in <module>
    from .core import *
ModuleNotFoundError: No module named 'mirage.core'

**Comment by jiazhihao** [comment]
Make sure you have installed `cython`. Otherwise, you will get a warning `WARNING: cython is not installed!!!`. We will convert this to an error message (instead of a warning)

**Comment by catid** [comment]
```
(mirage) ➜  mirage git:(main) ✗ python demo/demo_group_query_attention_spec_decode.py --checkpoint demo/checkpoint_group_query_attn_spec_decode.json
Traceback (most recent call last):
  File "/home/catid/sources/mirage/demo/demo_group_query_attention_spec_decode.py", line 1, in <module>
    import mirage as mi
  File "/home/catid/mambaforge/envs/mirage/lib/python3.10/site-packages/mirage-0.1.0-py3.10.egg/mirage/__init__.py", line 1, in <module>
    from .core import *
ModuleNotFoundError: No module named 'mirage.core'
(mirage) ➜  mirage git:(main) ✗ cython --version
Cython version 3.0.10
```

Cython is not the issue.  Seems to be something else

**Comment by Yang-YiFan** [comment]
I saw a similar error message when I'm trying the import
```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mirage as mi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/888/mirage/python/mirage/__init__.py", line 1, in <module>
    from .core import *
ModuleNotFoundError: No module named 'mirage.core'
```
